---
- name: Install and configure Zabbix Agent
  hosts: ubuntu.my
  become: yes
  tasks:

    # Update the apt package manager
    - name: Update apt repository
      apt:
        update_cache: yes

    # Install Zabbix Agent package
    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    # Retrieve the hostname of the server
    - name: Get the server hostname
      command: hostname
      register: hostname_output

    # Configure Zabbix Agent server
    - name: Configure Zabbix Agent server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=158.160.66.244'
        state: present
      notify:
        - Restart Zabbix Agent

    # Configure Zabbix Agent hostname using the retrieved hostname
    - name: Configure Zabbix Agent hostname
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ hostname_output.stdout }}"
        state: present
      notify:
        - Restart Zabbix Agent

    # Open necessary ports for Zabbix Agent
    - name: Allow Zabbix Agent port through UFW
      ufw:
        rule: allow
        port: 10050
        proto: tcp

    # Ensure the Zabbix Agent service is enabled and running
    - name: Ensure Zabbix Agent is running and enabled
      systemd:
        name: zabbix-agent
        enabled: yes
        state: started

  handlers:
    - name: Restart Zabbix Agent
      systemd:
        name: zabbix-agent
        state: restarted
