---
- name: Uninstall Zabbix Agent
  hosts: ubuntu.my
  become: yes
  tasks:

    # Stop the Zabbix Agent service
    - name: Stop Zabbix Agent service
      systemd:
        name: zabbix-agentd
        state: stopped
        enabled: no
      ignore_errors: yes

    # Remove Zabbix Agent package
    - name: Uninstall Zabbix Agent package
      apt:
        name: zabbix-agent
        state: absent
        purge: yes

    # Remove Zabbix Agent configuration files
    - name: Remove Zabbix Agent configuration files
      file:
        path: /etc/zabbix
        state: directory
        recurse: yes
      ignore_errors: yes

    # Remove Zabbix Agent logs
    - name: Remove Zabbix Agent logs
      file:
        path: /var/log/zabbix
        state: directory
        recurse: yes
      ignore_errors: yes

    # Remove Zabbix Agent from UFW rules
    - name: Remove Zabbix Agent port from UFW
      ufw:
        rule: deny
        port: 10050
        proto: tcp

    # Reload UFW to apply changes
    - name: Reload UFW
      command: ufw reload
      when: ansible_facts['os_family'] == 'Debian'
